steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build image
    args:
      - 'build'
      - '-t'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloudcoffee-repo/cloudcoffee-app:$SHORT_SHA'
      - '.'

  - name: 'gcr.io/cloud-builders/docker'
    id: Push image
    args:
      - 'push'
      - 'us-central1-docker.pkg.dev/$PROJECT_ID/cloudcoffee-repo/cloudcoffee-app:$SHORT_SHA'

  - name: 'gcr.io/cloud-builders/kubectl'
    id: Deploy to GKE
    args:
      - 'set'
      - 'image'
      - 'deployment/cloudcoffee'
      - 'cloudcoffee=us-central1-docker.pkg.dev/$PROJECT_ID/cloudcoffee-repo/cloudcoffee-app:$SHORT_SHA'
    env:
      - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=cloudcoffee-standard-cluster'

options:
  logging: CLOUD_LOGGING_ONLY
